"""add server_default to updated_at column

Revision ID: 25efc8fe108f
Revises: 36ff31fb4cc0
Create Date: 2025-12-30 23:01:06.977367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25efc8fe108f'
down_revision: Union[str, Sequence[str], None] = '36ff31fb4cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
