"""Add balance constraints to user model

Revision ID: 4720a6d27d83
Revises: c9dbb38ad56f
Create Date: 2026-01-10 13:24:10.110493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4720a6d27d83'
down_revision: Union[str, Sequence[str], None] = 'c9dbb38ad56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
