"""Add Income and Expense tables, with adding relationships

Revision ID: 738431246ec4
Revises: 8ad5b95ce2fc
Create Date: 2025-11-23 21:20:22.985444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738431246ec4'
down_revision: Union[str, Sequence[str], None] = '8ad5b95ce2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
