"""Add server defaults to updated_at columns

Revision ID: 755d6283296a
Revises: 25efc8fe108f
Create Date: 2025-12-30 23:04:11.839384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755d6283296a'
down_revision: Union[str, Sequence[str], None] = '25efc8fe108f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_check_constraint(None, 'expenses', sa.text("updated_at IS NOT NULL"))
    op.alter_column('incomes', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('incomes', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # Add triggers for onupdate
    op.execute("""
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$ language 'plpgsql';
    """)
    op.execute("""
    CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON expenses
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)
    op.execute("""
    CREATE TRIGGER update_incomes_updated_at BEFORE UPDATE ON incomes
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_incomes_updated_at ON incomes")
    op.execute("DROP TRIGGER IF EXISTS update_expenses_updated_at ON expenses")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")
    op.drop_constraint(None, 'expenses', type_='check')
    op.alter_column('incomes', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('incomes', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('expenses', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
