"""Change amount column to numeric

Revision ID: 91d1213ecda9
Revises: 84cb9c8bfe2b
Create Date: 2025-12-24 13:04:25.513184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d1213ecda9'
down_revision: Union[str, Sequence[str], None] = '84cb9c8bfe2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('incomes', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('savings', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('savings', 'current_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings', 'current_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('savings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('incomes', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
