"""add goal column to savings model

Revision ID: e6294f20a376
Revises: 4720a6d27d83
Create Date: 2026-01-10 15:12:52.560315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6294f20a376'
down_revision: Union[str, Sequence[str], None] = '4720a6d27d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('goal', sa.NUMERIC(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings', 'goal')
    # ### end Alembic commands ###
